looper_time = 0.02
pcm_id = 14

track_width = 0.4953
wheel_base = 0.5461

wheel_diameter = 0.0

drive_gear_ratio = 0.0
steer_gear_ratio = 0.0

[swerve.fl]
  drive = {
    motor_id = 8,
    enc_rev = false,
  }
  steer = {
    motor_id = 1,
    enc_rev = ,
    
    abs_enc_id = ,
    abs_enc_offset = 3.5450,
    abs_enc_rev = false,
  }

[swerve.fr]
  drive = {
    motor_id = 2,
    enc_rev = true,
  }
  steer = {
    motor_id = 3,
    enc_rev = ,
    
    abs_enc_id = ,
    abs_enc_offset = 1.6874,
    abs_enc_rev = false,
  }

[swerve.bl]
  drive = {
    motor_id = 4,
    enc_rev = false,
  }
  steer = {
    motor_id = 5,
    enc_rev = ,
    
    abs_enc_id = ,
    abs_enc_offset = 6.0700,
    abs_enc_rev = false,
  }

[swerve.br]
  drive = {
    motor_id = 6,
    enc_rev = true,
  }
  steer = {
    motor_id = 7,
    enc_rev = ,
    
    abs_enc_id = ,
    abs_enc_offset = 0.6259,
    abs_enc_rev = false,
  }
