looper_time = 0.02
pcm_id = 14

track_width = 0.4953
wheel_base = 0.5461

wheel_diameter = 0.0

drive_gear_ratio = 0.0
steer_gear_ratio = 0.0

[motors]
  # Drive motors
  fld = 8
  frd = 2
  bld = 4
  brd = 6

  # Steer motors
  fls = 1
  frs = 3
  bls = 5
  brs = 7

[encoders]
  fld_rev = false
  frd_rev = true
  bld_rev = false
  brd_rev = true

[absolute_encoders]
  fls_rev = false
  frs_rev = false
  bls_rev = false
  brs_rev = false

  fls_offset = 3.5450
  frs_offset = 1.6874
  bls_offset = 6.0700
  brs_offset = 0.6259
